reboot_gateway:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

wifi24ghz_enable:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    enabled:
      required: true
      default: True
      example: False
      selector:
        boolean:

wifi50ghz_enable:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    enabled:
      required: true
      default: True
      example: False
      selector:
        boolean:

set_wifi24ghz_power:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    power_level:
      required: true
      default: Full
      example: Half
      selector:
        select:
          options:
            - Full
            - Half

set_wifi50ghz_power:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    power_level:
      required: true
      default: Full
      example: Half
      selector:
        select:
          options:
            - Full
            - Half

get_client_list:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

set_client_hostname:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    mac_address:
      required: true
      example: 41:a4:df:7c:d1:c0
      selector:
        text:
    hostname:
      required: true
      example: homeassistant
      selector:
        text:

clear_client_hostname:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway
  fields:
    mac_address:
      required: true
      example: 41:a4:df:7c:d1:c0
      selector:
        text:

list_client_hostnames:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

get_access_point:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

get_gateway:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

get_gateway_clients:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

get_gateway_sim_card:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway

get_cell_status:
  target:
    entity:
      integration: tmobile_home_internet
      device_class: gateway


# set_wifi_ssid:
#   target:
#     entity:
#       integration: tmobile_home_internet
#       device_class: gateway
#   fields:
#     ssid:
#       required: true
#       example: "MyWifi"
#       selector:
#         text:
#           type: "text"
